theme: jekyll-theme-hacker
name: Simon Wheatcroft Guides
title: null
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  
  - README.md

  


  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
